[project]
name = "github-tracker"
version = "1.0.0"
description = "Jac client application: github-tracker"
entry-point = "main.jac"

[dependencies]
PyGithub = "2.5.0"
pandas = "2.2.0"
python-dotenv = "1.0.1"

[dependencies.npm]
jac-client-node = "1.0.4"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client]
